UNIT_TYPES = {
    "warrior": {
        "name": "Warriors",
        "icon": "⚔️",
        "category": "land",
        "attack": 2,
        "defense": 1,
        "moves": 1,
        "health": 100,
        "cost": 10,
        "era": "ancient",
        "requires_tech": None,
        "requires_building": "barracks",
        "description": "Basic melee unit. Cheap and quickly trained.",
    },
    "archer": {
        "name": "Archers",
        "icon": "🏹",
        "category": "land",
        "attack": 3,
        "defense": 2,
        "moves": 1,
        "health": 100,
        "cost": 15,
        "era": "ancient",
        "requires_tech": None,
        "requires_building": "barracks",
        "description": "Ranged unit. Can attack from a distance.",
    },
    "knight": {
        "name": "Knights",
        "icon": "🐴",
        "category": "land",
        "attack": 5,
        "defense": 3,
        "moves": 2,
        "health": 100,
        "cost": 30,
        "era": "medieval",
        "requires_tech": "chivalry",
        "requires_building": "barracks",
        "description": "Fast mounted warrior. High mobility.",
    },
    "musketeer": {
        "name": "Musketeers",
        "icon": "🔫",
        "category": "land",
        "attack": 6,
        "defense": 4,
        "moves": 1,
        "health": 100,
        "cost": 35,
        "era": "gunpowder",
        "requires_tech": "gunpowder",
        "requires_building": "barracks",
        "description": "Early gunpowder infantry unit.",
    },
    "infantry": {
        "name": "Infantry",
        "icon": "🪖",
        "category": "land",
        "attack": 8,
        "defense": 6,
        "moves": 1,
        "health": 100,
        "cost": 40,
        "era": "modern",
        "requires_tech": "military_science",
        "requires_building": "barracks",
        "description": "Modern foot soldier. Versatile and reliable.",
    },
    "tank": {
        "name": "Tank",
        "icon": "🚜",
        "category": "land",
        "attack": 16,
        "defense": 8,
        "moves": 3,
        "health": 100,
        "cost": 80,
        "era": "modern",
        "requires_tech": "mechanized_warfare",
        "requires_building": "barracks",
        "description": "Armored vehicle with heavy firepower.",
    },
    "artillery": {
        "name": "Artillery",
        "icon": "💥",
        "category": "land",
        "attack": 20,
        "defense": 4,
        "moves": 2,
        "health": 100,
        "cost": 70,
        "era": "modern",
        "requires_tech": "artillery_tech",
        "requires_building": "barracks",
        "description": "Long-range bombardment. Devastating but vulnerable.",
    },
    "fighter": {
        "name": "Fighter Jet",
        "icon": "✈️",
        "category": "air",
        "attack": 15,
        "defense": 10,
        "moves": 9,
        "health": 100,
        "cost": 120,
        "era": "modern",
        "requires_tech": "flight",
        "requires_building": "airbase",
        "description": "Aerial combat jet. High speed and range.",
    },
    "bomber": {
        "name": "Bomber",
        "icon": "💣",
        "category": "air",
        "attack": 25,
        "defense": 4,
        "moves": 8,
        "health": 100,
        "cost": 150,
        "era": "modern",
        "requires_tech": "advanced_flight",
        "requires_building": "airbase",
        "description": "Strategic bomber. Destroys infrastructure and cities.",
    },
    "destroyer": {
        "name": "Destroyer",
        "icon": "⚓",
        "category": "naval",
        "attack": 12,
        "defense": 10,
        "moves": 6,
        "health": 100,
        "cost": 100,
        "era": "modern",
        "requires_tech": "navigation",
        "requires_building": "harbor",
        "description": "Fast naval warship. Patrols sea lanes.",
    },
    "submarine": {
        "name": "Submarine",
        "icon": "🔱",
        "category": "naval",
        "attack": 18,
        "defense": 8,
        "moves": 5,
        "health": 100,
        "cost": 130,
        "era": "digital",
        "requires_tech": "nuclear",
        "requires_building": "harbor",
        "description": "Stealth underwater weapon. Nuclear-capable.",
    },
    "drone": {
        "name": "Combat Drone",
        "icon": "🛸",
        "category": "air",
        "attack": 14,
        "defense": 6,
        "moves": 10,
        "health": 100,
        "cost": 90,
        "era": "digital",
        "requires_tech": "ai_warfare",
        "requires_building": "airbase",
        "description": "Autonomous AI-controlled strike drone.",
    },
}

TECHNOLOGIES = {
    "agriculture": {
        "name": "Agriculture",
        "era": "ancient",
        "cost": 5,
        "x": 0,
        "y": 0,
        "description": "Enables organized crop farming and food surplus.",
        "requires": [],
        "unlocks_units": [],
        "unlocks_buildings": ["farm"],
        "bonus": "+10% food production",
    },
    "writing": {
        "name": "Writing",
        "era": "ancient",
        "cost": 5,
        "x": 0,
        "y": 2,
        "description": "Enables literacy, record keeping, and libraries.",
        "requires": [],
        "unlocks_units": [],
        "unlocks_buildings": ["library"],
        "bonus": "+5% research speed",
    },
    "bronze_working": {
        "name": "Bronze Working",
        "era": "ancient",
        "cost": 8,
        "x": 0,
        "y": 4,
        "description": "Enables bronze weapons, armor, and basic military.",
        "requires": [],
        "unlocks_units": ["warrior", "archer"],
        "unlocks_buildings": [],
        "bonus": "Unlocks Warriors and Archers",
    },
    "mathematics": {
        "name": "Mathematics",
        "era": "ancient",
        "cost": 10,
        "x": 1,
        "y": 2,
        "description": "Advanced calculation enables engineering and science.",
        "requires": ["writing"],
        "unlocks_units": [],
        "unlocks_buildings": ["monument"],
        "bonus": "+10% construction speed",
    },
    "feudalism": {
        "name": "Feudalism",
        "era": "medieval",
        "cost": 15,
        "x": 2,
        "y": 4,
        "description": "Hierarchical land system enables military vassals.",
        "requires": ["bronze_working"],
        "unlocks_units": [],
        "unlocks_buildings": ["castle"],
        "bonus": "+3 city defense",
    },
    "chivalry": {
        "name": "Chivalry",
        "era": "medieval",
        "cost": 20,
        "x": 3,
        "y": 4,
        "description": "Mounted warfare doctrine enables Knights.",
        "requires": ["feudalism"],
        "unlocks_units": ["knight"],
        "unlocks_buildings": [],
        "bonus": "Unlocks Knights",
    },
    "currency": {
        "name": "Currency",
        "era": "medieval",
        "cost": 15,
        "x": 2,
        "y": 0,
        "description": "Standardized money enables trade and taxation.",
        "requires": ["agriculture", "mathematics"],
        "unlocks_units": [],
        "unlocks_buildings": ["market"],
        "bonus": "+15% tax income",
    },
    "philosophy": {
        "name": "Philosophy",
        "era": "medieval",
        "cost": 15,
        "x": 2,
        "y": 2,
        "description": "Rational inquiry enables universities and governance.",
        "requires": ["writing", "mathematics"],
        "unlocks_units": [],
        "unlocks_buildings": ["university"],
        "bonus": "+20% research speed",
    },
    "gunpowder": {
        "name": "Gunpowder",
        "era": "gunpowder",
        "cost": 30,
        "x": 4,
        "y": 4,
        "description": "Explosive chemistry revolutionizes warfare.",
        "requires": ["chivalry", "currency"],
        "unlocks_units": ["musketeer"],
        "unlocks_buildings": ["barracks"],
        "bonus": "Unlocks Musketeers and Barracks",
    },
    "navigation": {
        "name": "Navigation",
        "era": "gunpowder",
        "cost": 30,
        "x": 4,
        "y": 0,
        "description": "Ocean navigation enables naval power.",
        "requires": ["currency", "philosophy"],
        "unlocks_units": ["destroyer"],
        "unlocks_buildings": ["harbor"],
        "bonus": "Unlocks Destroyers and Harbor",
    },
    "printing_press": {
        "name": "Printing Press",
        "era": "gunpowder",
        "cost": 25,
        "x": 4,
        "y": 2,
        "description": "Mass information dissemination transforms society.",
        "requires": ["philosophy"],
        "unlocks_units": [],
        "unlocks_buildings": ["newspaper"],
        "bonus": "+10% public approval",
    },
    "steam_power": {
        "name": "Steam Power",
        "era": "industrial",
        "cost": 40,
        "x": 5,
        "y": 3,
        "description": "Steam engines enable railways and factories.",
        "requires": ["gunpowder", "navigation"],
        "unlocks_units": [],
        "unlocks_buildings": ["factory", "railway_station"],
        "bonus": "+25% production speed",
    },
    "banking": {
        "name": "Banking",
        "era": "industrial",
        "cost": 35,
        "x": 5,
        "y": 1,
        "description": "Credit and investment accelerate economic growth.",
        "requires": ["currency", "printing_press"],
        "unlocks_units": [],
        "unlocks_buildings": ["bank"],
        "bonus": "+20% economic income",
    },
    "industrialization": {
        "name": "Industrialization",
        "era": "industrial",
        "cost": 45,
        "x": 6,
        "y": 2,
        "description": "Mass production transforms the economy.",
        "requires": ["steam_power", "banking"],
        "unlocks_units": [],
        "unlocks_buildings": ["power_plant"],
        "bonus": "+30% city production",
    },
    "military_science": {
        "name": "Military Science",
        "era": "modern",
        "cost": 50,
        "x": 7,
        "y": 4,
        "description": "Systematic warfare doctrine enables modern armies.",
        "requires": ["industrialization"],
        "unlocks_units": ["infantry"],
        "unlocks_buildings": [],
        "bonus": "Unlocks Infantry",
    },
    "artillery_tech": {
        "name": "Artillery",
        "era": "modern",
        "cost": 55,
        "x": 8,
        "y": 4,
        "description": "Heavy long-range bombardment weapons.",
        "requires": ["military_science"],
        "unlocks_units": ["artillery"],
        "unlocks_buildings": [],
        "bonus": "Unlocks Artillery",
    },
    "mechanized_warfare": {
        "name": "Mechanized Warfare",
        "era": "modern",
        "cost": 65,
        "x": 9,
        "y": 4,
        "description": "Armored vehicles and tanks dominate the battlefield.",
        "requires": ["military_science", "industrialization"],
        "unlocks_units": ["tank"],
        "unlocks_buildings": [],
        "bonus": "Unlocks Tanks",
    },
    "flight": {
        "name": "Flight",
        "era": "modern",
        "cost": 60,
        "x": 8,
        "y": 2,
        "description": "Powered aircraft enable air superiority.",
        "requires": ["industrialization", "military_science"],
        "unlocks_units": ["fighter"],
        "unlocks_buildings": ["airbase"],
        "bonus": "Unlocks Fighters and Airbase",
    },
    "advanced_flight": {
        "name": "Advanced Flight",
        "era": "modern",
        "cost": 70,
        "x": 9,
        "y": 2,
        "description": "Strategic bombing capability from long-range aircraft.",
        "requires": ["flight"],
        "unlocks_units": ["bomber"],
        "unlocks_buildings": [],
        "bonus": "Unlocks Bombers",
    },
    "nuclear": {
        "name": "Nuclear Power",
        "era": "digital",
        "cost": 80,
        "x": 10,
        "y": 3,
        "description": "Nuclear fission unlocks immense energy and weapons.",
        "requires": ["advanced_flight", "mechanized_warfare"],
        "unlocks_units": ["submarine"],
        "unlocks_buildings": ["nuclear_plant"],
        "bonus": "Unlocks Submarines and Nuclear Plant",
    },
    "electronics": {
        "name": "Electronics",
        "era": "digital",
        "cost": 70,
        "x": 10,
        "y": 1,
        "description": "Silicon circuits enable computers and communication.",
        "requires": ["flight", "banking"],
        "unlocks_units": [],
        "unlocks_buildings": ["internet_hub"],
        "bonus": "+15% all research speed",
    },
    "ai_warfare": {
        "name": "AI Warfare",
        "era": "digital",
        "cost": 100,
        "x": 11,
        "y": 2,
        "description": "Autonomous AI weapons and battlefield management.",
        "requires": ["nuclear", "electronics"],
        "unlocks_units": ["drone"],
        "unlocks_buildings": [],
        "bonus": "Unlocks Combat Drones",
    },
    "space_program": {
        "name": "Space Program",
        "era": "digital",
        "cost": 120,
        "x": 11,
        "y": 4,
        "description": "Satellite network and space exploration capability.",
        "requires": ["nuclear", "electronics"],
        "unlocks_units": [],
        "unlocks_buildings": ["space_center"],
        "bonus": "Unlocks Space Center, +20% all stats",
    },
}

BUILDING_TYPES = {
    "residential_low": {
        "name": "Low-Density Housing",
        "category": "zone",
        "icon": "🏠",
        "color": "#86efac",
        "cost": 50,
        "population_capacity": 100,
        "happiness": 5,
        "income": 10,
        "power_demand": 5,
        "water_demand": 5,
    },
    "residential_mid": {
        "name": "Mid-Density Housing",
        "category": "zone",
        "icon": "🏘️",
        "color": "#4ade80",
        "cost": 100,
        "population_capacity": 500,
        "happiness": 3,
        "income": 30,
        "power_demand": 15,
        "water_demand": 15,
    },
    "residential_high": {
        "name": "High-Rise Apartments",
        "category": "zone",
        "icon": "🏢",
        "color": "#16a34a",
        "cost": 200,
        "population_capacity": 2000,
        "happiness": -2,
        "income": 80,
        "power_demand": 50,
        "water_demand": 50,
    },
    "commercial": {
        "name": "Commercial Zone",
        "category": "zone",
        "icon": "🏪",
        "color": "#fde68a",
        "cost": 100,
        "population_capacity": 0,
        "happiness": 2,
        "income": 100,
        "power_demand": 30,
        "water_demand": 10,
    },
    "industrial": {
        "name": "Industrial Zone",
        "category": "zone",
        "icon": "🏭",
        "color": "#d1d5db",
        "cost": 150,
        "population_capacity": 0,
        "happiness": -5,
        "income": 200,
        "power_demand": 100,
        "water_demand": 30,
    },
    "road": {
        "name": "Road",
        "category": "infrastructure",
        "icon": "🛣️",
        "color": "#6b7280",
        "cost": 20,
        "population_capacity": 0,
        "happiness": 1,
        "income": 0,
        "power_demand": 0,
        "water_demand": 0,
    },
    "power_plant_coal": {
        "name": "Coal Power Plant",
        "category": "power",
        "icon": "⚡",
        "color": "#374151",
        "cost": 300,
        "population_capacity": 0,
        "happiness": -3,
        "income": -50,
        "power_supply": 200,
        "water_demand": 20,
    },
    "power_plant_solar": {
        "name": "Solar Farm",
        "category": "power",
        "icon": "☀️",
        "color": "#fbbf24",
        "cost": 500,
        "population_capacity": 0,
        "happiness": 5,
        "income": -20,
        "power_supply": 100,
        "water_demand": 0,
    },
    "power_plant_nuclear": {
        "name": "Nuclear Power Plant",
        "category": "power",
        "icon": "☢️",
        "color": "#7c3aed",
        "cost": 1000,
        "population_capacity": 0,
        "happiness": -10,
        "income": -100,
        "power_supply": 1000,
        "water_demand": 50,
        "requires_tech": "nuclear",
    },
    "water_tower": {
        "name": "Water Tower",
        "category": "infrastructure",
        "icon": "💧",
        "color": "#60a5fa",
        "cost": 100,
        "population_capacity": 0,
        "happiness": 3,
        "income": -10,
        "water_supply": 500,
        "power_demand": 5,
    },
    "police_station": {
        "name": "Police Station",
        "category": "service",
        "icon": "👮",
        "color": "#3b82f6",
        "cost": 200,
        "population_capacity": 0,
        "happiness": 5,
        "income": -30,
        "crime_reduction": 20,
        "power_demand": 10,
    },
    "fire_station": {
        "name": "Fire Station",
        "category": "service",
        "icon": "🚒",
        "color": "#ef4444",
        "cost": 150,
        "population_capacity": 0,
        "happiness": 3,
        "income": -20,
        "power_demand": 8,
    },
    "hospital": {
        "name": "Hospital",
        "category": "service",
        "icon": "🏥",
        "color": "#f87171",
        "cost": 400,
        "population_capacity": 0,
        "happiness": 8,
        "income": -50,
        "health_bonus": 15,
        "power_demand": 30,
    },
    "school": {
        "name": "School",
        "category": "service",
        "icon": "🏫",
        "color": "#a78bfa",
        "cost": 200,
        "population_capacity": 0,
        "happiness": 5,
        "income": -25,
        "education_bonus": 10,
        "power_demand": 15,
    },
    "park": {
        "name": "Park",
        "category": "service",
        "icon": "🌳",
        "color": "#bbf7d0",
        "cost": 80,
        "population_capacity": 0,
        "happiness": 10,
        "income": -5,
        "power_demand": 2,
    },
    "barracks": {
        "name": "Military Barracks",
        "category": "military",
        "icon": "🪖",
        "color": "#78350f",
        "cost": 300,
        "population_capacity": 0,
        "happiness": -2,
        "income": -40,
        "enables_units": ["warrior", "archer", "musketeer", "infantry", "knight", "tank", "artillery"],
        "power_demand": 20,
    },
    "airbase": {
        "name": "Air Force Base",
        "category": "military",
        "icon": "✈️",
        "color": "#1e3a5f",
        "cost": 600,
        "population_capacity": 0,
        "happiness": -3,
        "income": -80,
        "enables_units": ["fighter", "bomber", "drone"],
        "power_demand": 80,
        "requires_tech": "flight",
    },
    "harbor": {
        "name": "Naval Harbor",
        "category": "military",
        "icon": "⚓",
        "color": "#0c4a6e",
        "cost": 500,
        "population_capacity": 0,
        "happiness": 0,
        "income": -60,
        "enables_units": ["destroyer", "submarine"],
        "power_demand": 40,
        "requires_tech": "navigation",
    },
    "market": {
        "name": "Market",
        "category": "economy",
        "icon": "🛒",
        "color": "#f59e0b",
        "cost": 150,
        "population_capacity": 0,
        "happiness": 4,
        "income": 80,
        "power_demand": 10,
        "requires_tech": "currency",
    },
    "bank": {
        "name": "Bank",
        "category": "economy",
        "icon": "🏦",
        "color": "#d97706",
        "cost": 250,
        "population_capacity": 0,
        "happiness": 2,
        "income": 150,
        "power_demand": 15,
        "requires_tech": "banking",
    },
    "university": {
        "name": "University",
        "category": "education",
        "icon": "🎓",
        "color": "#7c3aed",
        "cost": 350,
        "population_capacity": 0,
        "happiness": 6,
        "income": -40,
        "education_bonus": 25,
        "power_demand": 25,
        "requires_tech": "philosophy",
    },
    "factory": {
        "name": "Factory",
        "category": "production",
        "icon": "⚙️",
        "color": "#6b7280",
        "cost": 400,
        "population_capacity": 0,
        "happiness": -4,
        "income": 250,
        "power_demand": 120,
        "requires_tech": "steam_power",
    },
    "nuclear_plant": {
        "name": "Nuclear Power Plant",
        "category": "power",
        "icon": "⚛️",
        "color": "#6d28d9",
        "cost": 800,
        "population_capacity": 0,
        "happiness": -8,
        "income": -80,
        "power_supply": 800,
        "requires_tech": "nuclear",
    },
    "space_center": {
        "name": "Space Center",
        "category": "science",
        "icon": "🚀",
        "color": "#1e1b4b",
        "cost": 1500,
        "population_capacity": 0,
        "happiness": 15,
        "income": -200,
        "power_demand": 200,
        "requires_tech": "space_program",
    },
}

TERRAIN_TYPES = {
    "ocean": {"color": "#1e40af", "movement_cost": 99, "defense_bonus": 0, "passable_land": False, "passable_naval": True},
    "coast": {"color": "#3b82f6", "movement_cost": 99, "defense_bonus": 0, "passable_land": False, "passable_naval": True},
    "plains": {"color": "#86efac", "movement_cost": 1, "defense_bonus": 0, "passable_land": True, "passable_naval": False},
    "grassland": {"color": "#4ade80", "movement_cost": 1, "defense_bonus": 0, "passable_land": True, "passable_naval": False},
    "desert": {"color": "#fbbf24", "movement_cost": 2, "defense_bonus": 0, "passable_land": True, "passable_naval": False},
    "forest": {"color": "#166534", "movement_cost": 2, "defense_bonus": 2, "passable_land": True, "passable_naval": False},
    "jungle": {"color": "#14532d", "movement_cost": 3, "defense_bonus": 3, "passable_land": True, "passable_naval": False},
    "mountain": {"color": "#78716c", "movement_cost": 99, "defense_bonus": 5, "passable_land": False, "passable_naval": False},
    "hills": {"color": "#a8a29e", "movement_cost": 2, "defense_bonus": 3, "passable_land": True, "passable_naval": False},
    "tundra": {"color": "#e2e8f0", "movement_cost": 2, "defense_bonus": 1, "passable_land": True, "passable_naval": False},
    "snow": {"color": "#f8fafc", "movement_cost": 3, "defense_bonus": 0, "passable_land": True, "passable_naval": False},
}

AI_COUNTRIES = [
    {"name": "Valdoria", "flag_color": "#dc2626", "personality": "aggressive"},
    {"name": "Elyndra", "flag_color": "#2563eb", "personality": "diplomatic"},
    {"name": "Thornheim", "flag_color": "#16a34a", "personality": "expansionist"},
    {"name": "Azureth", "flag_color": "#7c3aed", "personality": "peaceful"},
    {"name": "Drakmoor", "flag_color": "#d97706", "personality": "militaristic"},
    {"name": "Celestara", "flag_color": "#db2777", "personality": "scientific"},
    {"name": "Ironveil", "flag_color": "#475569", "personality": "industrial"},
    {"name": "Sunhaven", "flag_color": "#f59e0b", "personality": "cultural"},
]
